// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBdcq9sr4lVU7DKhkCn7ftWL6m6zjpiEuE',
    appId: '1:851296747336:web:2be9a878753c446407bd7d',
    messagingSenderId: '851296747336',
    projectId: 'market-e62c9',
    authDomain: 'market-e62c9.firebaseapp.com',
    databaseURL: 'https://market-e62c9-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'market-e62c9.appspot.com',
    measurementId: 'G-7YN7K40FL4',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDSswUlAxd1Gqp5x1Egf8_mor9Q99rwlOQ',
    appId: '1:851296747336:android:91b87dceb908793307bd7d',
    messagingSenderId: '851296747336',
    projectId: 'market-e62c9',
    databaseURL: 'https://market-e62c9-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'market-e62c9.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA4ZwF2Cwjsc-O9H9fo0BAxGCoqwA46FJI',
    appId: '1:851296747336:ios:77e98e99a01b5a7c07bd7d',
    messagingSenderId: '851296747336',
    projectId: 'market-e62c9',
    databaseURL: 'https://market-e62c9-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'market-e62c9.appspot.com',
    iosBundleId: 'com.example.nisokoVendors',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyA4ZwF2Cwjsc-O9H9fo0BAxGCoqwA46FJI',
    appId: '1:851296747336:ios:77e98e99a01b5a7c07bd7d',
    messagingSenderId: '851296747336',
    projectId: 'market-e62c9',
    databaseURL: 'https://market-e62c9-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'market-e62c9.appspot.com',
    iosBundleId: 'com.example.nisokoVendors',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyB3kauooDKV3NEAdjozt5bJonMO3da3b_E',
    appId: '1:851296747336:web:05667440c2a5449407bd7d',
    messagingSenderId: '851296747336',
    projectId: 'market-e62c9',
    authDomain: 'market-e62c9.firebaseapp.com',
    databaseURL: 'https://market-e62c9-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'market-e62c9.appspot.com',
    measurementId: 'G-CPXKN67KMZ',
  );

}